---
abstract: 'WWW::Bing::Search - Parser of Bing Search Engine search results'
author:
  - 'Dmitry Vinogradenko <jin@hungosh.net>'
build_requires:
  Test::Most: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
license: perl
meta-spec:
  version: 0.010
name: WWW-Bing-Search
requires:
  LWP::UserAgent: 0
version: 0.010
